language: python
python:
  #  Python Version to be used
  - "3.6"
install:
  #  Use Requirements.txt to install dependencies in virtual env
  - pip install -r requirements.txt
  # Setup testing library in virtual env
  - pip install pytest
  - pip install python-coveralls
  - pip install pytest-cov
script:
  - pytest  --cov api/v1 tests/ -v --cov-report term-missing
after_success:
  - coveralls